let items = [
    {
        id:1,
        lesson:"Art",
        location:"London",
        price:22,
        spaces:5,
        image:"assets/art.jpg"
    },
    {
        id:2,
        lesson:"cooking",
        location:"Oxford",
        price:19,
        spaces:5,
        image:"assets/cookinng.png"
    },
    {
        id:3,
        lesson:"English",
        location:"London",
        price:20,
        spaces:5,
        image:"assets/english.jpg"
    },
    {
        id:4,
        lesson:"Football",
        location:"York",
        price:17,
        spaces:5,
        image:"assets/football.png"
    },
    {
        id:5,
        lesson:"French",
        location:"Bristol",
        price:7,
        spaces:5,
        image:"assets/french.jpg"
    },
    {
        id:6,
        lesson:"German",
        location:"London",
        price:8,
        spaces:5,
        image:"assets/german.jpg"
    },
    {
        id:7,
        lesson:"Math",
        location:"Manchester",
        price:12,
        spaces:5,
        image:"assets/math symbol.png"
    },
    {
        id:8,
        lesson:"Robot",
        location:"Liverpool",
        price:9,
        spaces:5,
        image:"assets/robot.png"
    },
    {
        id:9,
        lesson:"Swimming",
        location:"London",
        price:13,
        spaces:5,
        image:"assets/swimming.jpg"
    },
    {
        id:10,
        lesson:"Tailor",
        location:"Chelsey",
        price:16,
        spaces:5,
        image:"assets/tailoring.jpg"
    }
]